//! The per-call session secret.
//!
//! 32 random bytes, generated by the server, carried to the client in the
//! connection string, and used directly as the **Noise_NNpsk0 PSK**. It both
//! authenticates the peer and keys the channel, so no certs/PKI are needed.
//! Held in `Zeroizing` and never logged / `Debug`-printed (the deny-list).
//! Single-use + TTL is enforced by the server's connection lifecycle (it
//! accepts exactly one handshake within a bounded window — see
//! `endpoint::accept_server`), so there is no long-lived secret table.

use std::fmt;

use base64::Engine;
use zeroize::Zeroizing;

/// The fixed secret length (= the Noise PSK length).
pub const SECRET_LEN: usize = 32;

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum SecretError {
    #[error("session secret is not valid base64url")]
    Base64,
    #[error("session secret must be {SECRET_LEN} bytes, got {0}")]
    Length(usize),
    #[error("OS CSPRNG unavailable")]
    Rng,
}

/// A per-call session secret. The bytes are zeroized on drop and never appear
/// in `Debug`/logs.
#[derive(Clone)]
pub struct SessionSecret(Zeroizing<Vec<u8>>);

impl SessionSecret {
    /// Generate a fresh 32-byte secret from the OS CSPRNG.
    pub fn generate() -> Result<Self, SecretError> {
        let mut bytes = vec![0u8; SECRET_LEN];
        getrandom::getrandom(&mut bytes).map_err(|_| SecretError::Rng)?;
        Ok(Self(Zeroizing::new(bytes)))
    }

    /// The raw bytes — feed straight into the Noise PSK slot.
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }

    /// Encode as base64url-without-padding for the connection-string fragment.
    pub fn to_base64url(&self) -> String {
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(&*self.0)
    }

    /// Decode from the connection string; rejects anything not exactly 32 bytes.
    pub fn from_base64url(s: &str) -> Result<Self, SecretError> {
        let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(s.trim())
            .map_err(|_| SecretError::Base64)?;
        if bytes.len() != SECRET_LEN {
            return Err(SecretError::Length(bytes.len()));
        }
        Ok(Self(Zeroizing::new(bytes)))
    }
}

impl fmt::Debug for SessionSecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Never reveal the secret (deny-list).
        f.write_str("SessionSecret(***)")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_is_32_bytes_and_random() {
        let a = SessionSecret::generate().unwrap();
        let b = SessionSecret::generate().unwrap();
        assert_eq!(a.as_bytes().len(), SECRET_LEN);
        assert_ne!(a.as_bytes(), b.as_bytes(), "two secrets must differ");
    }

    #[test]
    fn base64url_round_trips() {
        let s = SessionSecret::generate().unwrap();
        let encoded = s.to_base64url();
        assert!(!encoded.contains('='), "no padding");
        assert!(
            !encoded.contains('+') && !encoded.contains('/'),
            "url-safe alphabet"
        );
        let back = SessionSecret::from_base64url(&encoded).unwrap();
        assert_eq!(s.as_bytes(), back.as_bytes());
    }

    #[test]
    fn decode_rejects_wrong_length_and_junk() {
        let short = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode([0u8; 16]);
        assert!(matches!(
            SessionSecret::from_base64url(&short),
            Err(SecretError::Length(16))
        ));
        assert!(matches!(
            SessionSecret::from_base64url("!!!notbase64"),
            Err(SecretError::Base64)
        ));
    }

    #[test]
    fn debug_never_leaks() {
        let s = SessionSecret::generate().unwrap();
        assert_eq!(format!("{s:?}"), "SessionSecret(***)");
    }
}
